version: '3'

#Build only (put your images in here)
services:
  databox-store-blob-mongo:
    build: 
        context: ./databox-store-blob-mongo
        dockerfile: Dockerfile
    image: databox-store-blob-mongo
  databox-store-blob:
    build: 
        context: ./databox-store-blob
        dockerfile: Dockerfile
    image: databox-store-blob

#An exmaple of how to add your code to databox
  databox-os-monitor-driver:
    build: 
        context: ./databox-os-monitor-driver
        dockerfile: Dockerfile
    image: databox-os-monitor-driver
